export default [
  {
    img: "Card-1.png",
    title: "Life Lessons With Katie",
    reviews: 8,
    rating: 5,
    country: "USA",
    price: 589,
    openspots: 0,
  },
  {
    img: "Card-2.jpg",
    title: "Gymnastics with Shekar",
    reviews: 10,
    rating: 4,
    country: "Mexico",
    price: 200,
    openspots: 10,
  },
  {
    img: "Card-3.jpg",
    title: "Education System by Karan",
    reviews: 100,
    rating: 10,
    country: "India",
    price: 1800,
    openspots: 10,
  },
  {
    img: "Card-4.jpg",
    title: "Travelling Experiences With Nayab",
    reviews: 2,
    rating: 5,
    country: "Online",
    price: 600,
    openspots: 2,
  },
];
